import type { Metadata } from "next";
import localFont from "next/font/local";
import { Oswald } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "./components/ThemeProviderWrapper";

// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: ["400", "700"],
});

const myriadPro = localFont({
  src: [
    {
      path: "./fonts/myriad-pro-webfont/MYRIADPRO-REGULAR.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/myriad-pro-webfont/MYRIADPRO-BOLD.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-myriad-pro",
});

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${myriadPro.variable} ${oswald.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
      </body>
    </html>
  );
}
